version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    docker:
      - image: circleci/hello-build@0.0.7
    steps:
      - checkout
      - run: npm test

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
          - build

