version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie

    steps:
      - run: echo "hello"

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
          - build

